import {
  APP_FEATURES as FEATURES,
  APP_HTML_ELEMENTS as HTML_ELEMENTS,
} from '~core/constants';

export const REPORT_ID = {
  BUTTON_SEARCH: `${FEATURES.REPORTS}-${HTML_ELEMENTS.BUTTON}-search`,
  REPORT_LIST: `${FEATURES.REPORTS}-${HTML_ELEMENTS.TABLE}-reportList`,
  REPORT_LIST_NOT_FOUND: `${FEATURES.REPORTS}-${HTML_ELEMENTS.TABLE}-empty`,
  REPORT_MAIN_SECTION: `${FEATURES.REPORTS}`,
};
