const LOCAL_STORAGE_PREFIX_KEY = 'CRM';

export const LOCAL_STORAGE_KEYS = {
  OAUTH2_TOKEN: `${LOCAL_STORAGE_PREFIX_KEY}_OAUTH2_TOKEN`,
  CURRENT_USER: `${LOCAL_STORAGE_PREFIX_KEY}_CURRENT_USER`,
};
