import {
  APP_FEATURES as FEATURES,
  APP_HTML_ELEMENTS as HTML_ELEMENTS,
} from '~core/constants';

export const TASK_ID = {
  BUTTON_CANCEL: `${FEATURES.TASKS}-${HTML_ELEMENTS.BUTTON}-cancel`,
  BUTTON_CLOSE: `${FEATURES.TASKS}-${HTML_ELEMENTS.BUTTON}-close`,
  BUTTON_CREATE: `${FEATURES.TASKS}-${HTML_ELEMENTS.BUTTON}-create`,
  BUTTON_DELETE: `${FEATURES.TASKS}-${HTML_ELEMENTS.BUTTON}-delete`,
  BUTTON_SUBMIT: `${FEATURES.TASKS}-${HTML_ELEMENTS.BUTTON}-submit`,

  TASK_DETAILS_LIST: `${FEATURES.TASKS}-${HTML_ELEMENTS.LIST}-details`,
  TASK_DETAILS: `${FEATURES.TASKS}-details`,
  TASK_DIALOG: `${FEATURES.TASKS}-dialog`,
  TASK_FORM_CREATE: `${FEATURES.TASKS}-${HTML_ELEMENTS.FORM}-create`,
  TASK_FORM_EDIT: `${FEATURES.TASKS}-${HTML_ELEMENTS.FORM}-edit`,
  TASK_LIST_NOT_FOUND: `${FEATURES.TASKS}-${HTML_ELEMENTS.TABLE}-empty`,
  TASK_LIST_PAGINATION: `${FEATURES.TASKS}-${HTML_ELEMENTS.PAGINATION}-taskList`,
  TASK_LIST: `${FEATURES.TASKS}-${HTML_ELEMENTS.TABLE}-taskList`,
  TASK_MAIN_SECTION: `${FEATURES.TASKS}`,

  TOAST_ADD_FAILED: `${FEATURES.TASKS}-${HTML_ELEMENTS.NOTIFICATION}-addFailed`,
  TOAST_ADD_SUCCESS: `${FEATURES.TASKS}-${HTML_ELEMENTS.NOTIFICATION}-addSuccess`,
  TOAST_DELETE_FAILED: `${FEATURES.TASKS}-${HTML_ELEMENTS.NOTIFICATION}-deleteFailed`,
  TOAST_DELETE_SUCCESS: `${FEATURES.TASKS}-${HTML_ELEMENTS.NOTIFICATION}-deleteSuccess`,
  TOAST_UPDATE_FAILED: `${FEATURES.TASKS}-${HTML_ELEMENTS.NOTIFICATION}-updateFailed`,
  TOAST_UPDATE_SUCCESS: `${FEATURES.TASKS}-${HTML_ELEMENTS.NOTIFICATION}-updateSuccess`,
};
