import {
  APP_FEATURES as FEATURES,
  APP_HTML_ELEMENTS as HTML_ELEMENTS,
} from '~core/constants';

/* Define specific Ids for UI elements */
export const PRODUCT_ID = {
  BUTTON_CANCEL: `${FEATURES.PRODUCTS}-${HTML_ELEMENTS.BUTTON}-cancel`,
  BUTTON_CLOSE: `${FEATURES.PRODUCTS}-${HTML_ELEMENTS.BUTTON}-close`,
  BUTTON_CREATE: `${FEATURES.PRODUCTS}-${HTML_ELEMENTS.BUTTON}-create`,
  BUTTON_DELETE_MULTIPLE: `${FEATURES.PRODUCTS}-${HTML_ELEMENTS.BUTTON}-deleteMultiple`,
  BUTTON_DELETE: `${FEATURES.PRODUCTS}-${HTML_ELEMENTS.BUTTON}-delete`,
  BUTTON_SUBMIT: `${FEATURES.PRODUCTS}-${HTML_ELEMENTS.BUTTON}-submit`,

  PRODUCT_DETAILS_LIST: `${FEATURES.PRODUCTS}-${HTML_ELEMENTS.LIST}-details`,
  PRODUCT_DETAILS: `${FEATURES.PRODUCTS}-details`,
  PRODUCT_DIALOG: `${FEATURES.PRODUCTS}-dialog`,
  PRODUCT_FORM_CREATE: `${FEATURES.PRODUCTS}-${HTML_ELEMENTS.FORM}-create`,
  PRODUCT_FORM_EDIT: `${FEATURES.PRODUCTS}-${HTML_ELEMENTS.FORM}-edit`,
  PRODUCT_LIST_NOT_FOUND: `${FEATURES.PRODUCTS}-${HTML_ELEMENTS.TABLE}-empty`,
  PRODUCT_LIST_PAGINATION: `${FEATURES.PRODUCTS}-${HTML_ELEMENTS.PAGINATION}-productList`,
  PRODUCT_LIST: `${FEATURES.PRODUCTS}-${HTML_ELEMENTS.TABLE}-productList`,
  PRODUCT_MAIN_SECTION: `${FEATURES.PRODUCTS}`,

  INPUT_SEARCH: `${FEATURES.PRODUCTS}-${HTML_ELEMENTS.FORM}-search`,

  TOAST_ADD_FAILED: `${FEATURES.PRODUCTS}-${HTML_ELEMENTS.NOTIFICATION}-addFailed`,
  TOAST_ADD_SUCCESS: `${FEATURES.PRODUCTS}-${HTML_ELEMENTS.NOTIFICATION}-addSuccess`,
  TOAST_DELETE_FAILED: `${FEATURES.PRODUCTS}-${HTML_ELEMENTS.NOTIFICATION}-deleteFailed`,
  TOAST_DELETE_MULTIPLE_FAILED: `${FEATURES.PRODUCTS}-${HTML_ELEMENTS.NOTIFICATION}-deleteMultipleFailed`,
  TOAST_DELETE_MULTIPLE_SUCCESS: `${FEATURES.PRODUCTS}-${HTML_ELEMENTS.NOTIFICATION}-deleteMultipleSuccess`,
  TOAST_DELETE_SUCCESS: `${FEATURES.PRODUCTS}-${HTML_ELEMENTS.NOTIFICATION}-deleteSuccess`,
  TOAST_UPDATE_FAILED: `${FEATURES.PRODUCTS}-${HTML_ELEMENTS.NOTIFICATION}-updateFailed`,
  TOAST_UPDATE_SUCCESS: `${FEATURES.PRODUCTS}-${HTML_ELEMENTS.NOTIFICATION}-updateSuccess`,
};
